create table public.site_configuration (
  singleton boolean primary key default true check (singleton),
  max_gda integer not null default 35 check (max_gda between 1 and 200),
  roster_publish_time time without time zone not null default time '20:00:00',
  updated_by_profile_id bigint references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.site_configuration (singleton, max_gda, roster_publish_time)
values (true, 35, time '20:00:00');

create table public.navigation_links (
  id bigint generated by default as identity primary key,
  external_id uuid not null default gen_random_uuid() unique,
  category text not null check (category in ('LIENS_UTILES', 'INSTRUCTEUR')),
  label text not null check (char_length(btrim(label)) between 1 and 100),
  url text not null check (url ~* '^https?://'),
  display_mode text not null default 'IFRAME' check (display_mode in ('IFRAME', 'EXTERNAL')),
  sort_order integer not null default 0 check (sort_order between 0 and 10000),
  active boolean not null default true,
  created_by_profile_id bigint references public.profiles(id) on delete set null,
  updated_by_profile_id bigint references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index navigation_links_category_order_idx
  on public.navigation_links (category, active, sort_order, id);

create index navigation_links_created_by_profile_idx
  on public.navigation_links (created_by_profile_id);

create index navigation_links_updated_by_profile_idx
  on public.navigation_links (updated_by_profile_id);

create index site_configuration_updated_by_profile_idx
  on public.site_configuration (updated_by_profile_id);

insert into public.navigation_links (category, label, url, display_mode, sort_order)
values
  ('LIENS_UTILES', 'Règlement GDA', 'https://docs.google.com/document/d/1w2HBmk0RJdvvOpNMIZAMVUFpqUNaYaICc9SgZDBYrzA/preview', 'IFRAME', 10),
  ('LIENS_UTILES', 'Guide GDA', 'https://sites.google.com/view/guide-gda/guide?authuser=0', 'EXTERNAL', 20),
  ('LIENS_UTILES', 'Cours martial', 'https://docs.google.com/document/d/1bow1cKtKiLF3Z83qvz9XSoERj5IGiwj7MAVvhUfshAA/preview', 'IFRAME', 30),
  ('INSTRUCTEUR', 'Règlement instructeur', 'https://docs.google.com/document/d/1g1QKhrcpjdNO6pQ1OUS9foEXCd0wkRIieAeVe1Y8Wos/preview', 'IFRAME', 10);

create trigger site_configuration_set_updated_at
before update on public.site_configuration
for each row execute function app_private.set_updated_at();

create trigger navigation_links_set_updated_at
before update on public.navigation_links
for each row execute function app_private.set_updated_at();

alter table public.site_configuration enable row level security;
alter table public.navigation_links enable row level security;

revoke all on table public.site_configuration from public, anon, authenticated;
revoke all on table public.navigation_links from public, anon, authenticated;
revoke all on sequence public.navigation_links_id_seq from public, anon, authenticated;
grant select, insert, update, delete on table public.site_configuration to service_role;
grant select, insert, update, delete on table public.navigation_links to service_role;
grant usage, select on sequence public.navigation_links_id_seq to service_role;

create or replace function app_private.publish_gda_roster_planifie()
returns bigint
language plpgsql
set search_path = ''
as $function$
declare
  v_maintenant timestamptz := clock_timestamp();
  v_maintenant_paris timestamp := timezone('Europe/Paris', v_maintenant);
  v_heure_publication time := time '20:00:00';
  v_version_id bigint;
begin
  select configuration.roster_publish_time
  into v_heure_publication
  from public.site_configuration as configuration
  where configuration.singleton = true;

  if to_char(v_maintenant_paris, 'HH24:MI') <> to_char(v_heure_publication, 'HH24:MI') then
    return null;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('gda_roster_daily_europe_paris', 0)
  );

  select version.id
  into v_version_id
  from public.gda_roster_versions as version
  where timezone('Europe/Paris', version.published_at)::date = v_maintenant_paris::date
    and timezone('Europe/Paris', version.published_at)::time >= v_heure_publication
  order by version.published_at desc, version.id desc
  limit 1;

  if v_version_id is not null then
    return v_version_id;
  end if;

  return app_private.publish_gda_roster_snapshot(
    'Actualisation automatique quotidienne à ' || to_char(v_heure_publication, 'HH24:MI'),
    null
  );
end;
$function$;

revoke all on function app_private.publish_gda_roster_planifie()
  from public, anon, authenticated, service_role;

do $block$
declare
  v_job record;
begin
  for v_job in
    select jobid
    from cron.job
    where jobname in ('publier-effectif-gda-20h-paris', 'publier-effectif-gda-planifie-paris')
  loop
    perform cron.unschedule(v_job.jobid);
  end loop;
end;
$block$;

select cron.schedule(
  'publier-effectif-gda-planifie-paris',
  '* * * * *',
  $cron$select app_private.publish_gda_roster_planifie();$cron$
);
